### ISSUE TITLE
Packages missing in DESCRIPTION?

### ISSUE THREAD

**Issue by andybeet** [EmilyMarkowitz-NOAA/NMFSReports#1]
`packrat`, and `RMarkReports`  included in the DESCRIPTION `Imports`?

And `nmfspalette`  added to DESCRIPTION `Remotes`

For example: 
When sourcing `run.r` an error arises:
``` 
Error in citation("nmfspalette") : 
  there is no package called ‘nmfspalette’ 
```

**Comment by EmilyMarkowitz-NOAA** [comment]
Not sure how I missed this for this long, but resolved ages ago. Thanks for checking this and submitting this issue. Those packages have been removed from the description since I don't require or use them any more.
